## 1. 벡터, 행렬 그리고 텐서
 - 딥 러닝을 하게 되면 다루게되는 가장 기본적인 단위는 벡터, 행렬, 텐서입니다.
 - 1차원으로 구성된 값을 벡터, 2차원으로 구성된 값을 행렬, 3차원이 되면 텐서라고 부릅니다.
 - 사실 딥 러닝을 할때 다루고 있는 행렬 또는 텐서의 크기를 고려하는 것은 항상 중요합니다.
 - 앞으로 다루게 되는 텐서는 다음과 같은 방법으로 표기합니다. 2차원 텐서를 예로 들겠습니다.
    - 2치원 텐서 : (배치사이즈, 크기)
    - 3차원 텐서 : (배치사이즈, 가로크기, 세로크기)
    - 항상 배치사이즈가 가장 먼저 온다는 것을 명심하세요.
    - 배치사이즈는 컴퓨터가 한번에 처리할 데이터의 수를 의미합니다.

## 2. 넘파이로 텐서 만들기 (벡터와 행렬 만들기)
 - PyTorch로 텐서를 만들어보기 전에 우선 Numpy로 텐서를 만들어보겠습니다. 

#### 1) 1D with Numpy


In [1]:
import numpy as np

In [4]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


 - 이제 1차원 벡터의 차원과 크기를 출력해보겠습니다.

In [7]:
print('Rank of t : ', t.ndim)  ## .ndim은 몇차원인가?
print('Shape of t: ', t.shape) ## .shape는 크기가 몇인가?
### (7, )의 형식은 (1X7)크기를 의미합니다.

Rank of t :  1
Shape of t:  (7,)


#### 2) 2D with Numpy

In [10]:
t = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(t)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
print('Rank of t : ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t :  2
Shape of t:  (4, 3)


## 3. 파이토치 텐서 선언하기
 - 이쯤에서 넘파이와 비교를 위해 파이토치로 텐서를 선언합니다.

#### 1) 1D with PyTorch

In [14]:
import torch

In [17]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [18]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


## 2) 2D with PyTorch

In [20]:
t = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [21]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


## 3) 브로드캐스팅(Broadcasting)
 - 딥 러닝을 하게되면 불가피하게 크기가 다른 행렬 또는 텐서에 대해서 사칙연산 을 수행해야 할 필요가 있는 경우가 생갑니다. 이를 위해 파이토치에서는 자동으로 크기를 맞춰서 연산을 수행하게 만드는 브로드캐스팅이라는 기능을 제공합니다.

In [23]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


 - 위의 경우는 m1과 m2 모두 크기가 (1, 2)입니다. 그래서 문제 없이 덧셈연산이 가능합니다.
 - 하지만 크기가 다른 경우는 파이토치가 알아서 브로드캐스팅을 진행하여 연산가능하게 합니다.

In [25]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])  ## [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


 - 위는 스칼라 값의 텐서를 (1, 2)로 브로드캐스팅하여 덧셈을 수행하였습니다.
 - 다음과 같은 경우도 볼까요?

In [27]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

## [1, 2]        >>  [ [1, 2], [1, 2] ]
## [ [3], [4] ]  >>  [ [3, 3], [4, 4] ]

tensor([[4., 5.],
        [5., 6.]])


 - 브로드캐스팅은 편리하지만, 자동으로 실행되는 기능이므로 매우 주의하여 사용하여야 합니다. 브로드캐스팅에 의하여 의도치않은 연산이 수행된다면 어디서 문제가 발생했는지 찾기가 매우 힘들어집니다.

## 4. 자주 사용되는 기능

#### 1) 행렬 곱셈과 곱셈의 차이
 - 행렬로 곱셈을 하는 방법은 크게 두 가지가 있습니다. 바로 행렬곱셈(.matmul)과 원소 별 곱셈(.mul)입니다.

In [29]:
m1 = torch.FloatTensor([ [1, 2], [3, 4] ])
m2 = torch.FloatTensor([ [1], [2] ])
print(m1.matmul(m2))

tensor([[ 5.],
        [11.]])


 - 위 결과는 2X2 행렬과 2X1행렬의 곱셈결과를 보여줍니다.
 - 다음 곱셈은 행렬 곱셈이 아닌 원소끼리 곱셈입니다.

In [31]:
m1 = torch.FloatTensor([ [1, 2], [3, 4] ])
m2 = torch.FloatTensor([ [5, 6], [7, 8] ])

print(m1.mul(m2))

tensor([[ 5., 12.],
        [21., 32.]])


#### 2) 평균
 - 평균은 Numpy에서의 사용법과 매우 유사합니다.

In [33]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


 - 차원을 기준으로 평균을 구할 수 있습니다.
 - `dim=0` 이라는 옵션은 첫번째 차원을 제거하라는 뜻으로 이해하면 될겁니다.
 - `dim=1`은 반대로 두번쨰 차원을 제거하라는 뜻으로 이해하면 되겟죠?



In [35]:
t = torch.FloatTensor([ [1, 2], [3, 4], [5, 6] ])
print(t.mean(dim=0))
print(t.mean(dim=1))

tensor([3., 4.])
tensor([1.5000, 3.5000, 5.5000])


#### 3) 덧셈
 - 덧셈의 경우도 평균과 매우 유사합니다.

In [36]:
t = torch.FloatTensor([ [1, 2], [3, 4], [5, 6] ])
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor([ 9., 12.])
tensor([ 3.,  7., 11.])


#### 4) 최대(max)와 아그맥스(ArgMax)
 - 최대(max)는 원소의 최대값을 리턴하고, 아그맥스(Argmax)는 최댓값을 가진 인덱스를 리턴합니다.

In [41]:
t = torch.FloatTensor( [[1, 2], [3, 4]] )
print(t)
print(t.max())
print(t.max(dim=0))

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


 - max에서 dim옵션을 선언하면 argmax값 그러니까 가장큰 index를 반환합니다.