# 인덱싱, 데이터조작, 인덱스조작

    - df.loc[행, 열]    :  index의 번호가 아니라 index의 이름으로 데이터에 접근할 수 있는 함수
    - df.iloc[행, 열]   :  index의 번호(index의 순서)로 데이터에 접근할 수 있는 함수

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
sample_df = pd.DataFrame(np.arange(10, 22).reshape(3, 4),
                         index   = ['a', 'b', 'c'],
                         columns = ['A', 'B', 'C', 'D'])
sample_df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

## 1. df.loc['행이름', '열이름']

In [14]:
# df.loc['행 index 이름']
display(sample_df.loc['a'])
print()

display(type(sample_df.loc['a']))
print()

display(sample_df.loc['a'].values)
print()

display(type(sample_df.loc['a'].values))
print()

A    10
B    11
C    12
D    13
Name: a, dtype: int32

pandas.core.series.Series

array([10, 11, 12, 13])

numpy.ndarray

In [15]:
sample_df.loc['b' : 'c']

A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [19]:
display(sample_df)
display(sample_df.A) # 행이 아닌 열의 경우 이렇게 칼럼을 불러 올 수도 있다. 신기하네
display(type(sample_df.A))

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

a    10
b    14
c    18
Name: A, dtype: int32

pandas.core.series.Series

In [24]:
sample_df.loc[ sample_df.A > 15 ]

A   B   C   D
c  18  19  20  21

In [27]:
sample_df2 = pd.DataFrame(np.arange(10, 26).reshape(4, 4),
                         columns = ['A', 'B', 'C', 'D'])
sample_df2

A   B   C   D
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25

In [30]:
sample_df2.loc[1:2]

A   B   C   D
1  14  15  16  17
2  18  19  20  21

In [31]:
sample_df.loc['a', 'A']

10

In [39]:
display(sample_df)
display(sample_df.loc['b' : 'c', 'A'].values)
display(sample_df.loc['a', :].values)
display(sample_df.loc['b' : 'c', 'C' : 'D'])

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

array([14, 18])

array([10, 11, 12, 13])

C   D
b  16  17
c  20  21

 ## 2. df.iloc[행순서, 열순서]

In [40]:
sample_df = pd.DataFrame(np.arange(10, 22).reshape(3, 4),
                         index   = ['a', 'b', 'c'],
                         columns = ['A', 'B', 'C', 'D'])
sample_df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [48]:
display(sample_df)
display(sample_df.iloc[0, 2:4].values)
display(sample_df.iloc[0, -2:].values)
display(sample_df.iloc[2, 1:3].values)

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

array([12, 13])

array([12, 13])

array([19, 20])

###### 데이터 갯수를 세알려보자
   - count()
       > - axis=0 : 가로방향으로 개수 세어줌
       > - axis=1 : 세로방향으로 개수 세어줌

In [52]:
s = pd.Series(range(10))
display(s)
display(s.count())

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

10

In [54]:
# count() 함수는 NaN값 (결측치)를 세지 않는다.
s[5] = np.NaN
s[2] = np.NaN
display(s.count())

8

In [56]:
np.random.seed(123)
count_df = pd.DataFrame(np.random.randint(5, size=(4, 4)), dtype=np.float)
display(count_df)

0    1    2    3
0  2.0  4.0  2.0  1.0
1  3.0  2.0  3.0  1.0
2  1.0  0.0  1.0  1.0
3  0.0  0.0  1.0  3.0

In [84]:
# 임의로 NaN값을 한번 넣어보자
random_col = np.random.choice(3, replace=False, size=2)
random_row = np.random.choice(3, replace=False, size=2)

for col in random_col :
    for row in random_row :
        count_df.iloc[row, col] = np.NaN
display(count_df)
display(count_df.count(axis= 0))

0    1    2    3
0  NaN  NaN  NaN  1.0
1  NaN  NaN  NaN  1.0
2  NaN  NaN  NaN  1.0
3  0.0  0.0  1.0  3.0

0    1
1    1
2    1
3    4
dtype: int64

In [41]:
import seaborn as sns
titanic = sns.load_dataset('titanic')

In [4]:
type(titanic)

pandas.core.frame.DataFrame

In [5]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [42]:
display(titanic.count(axis=0))  # 열방향
display(titanic.count(axis=1))  # 행방향

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

0      14
1      15
2      14
3      15
4      14
       ..
886    14
887    15
888    13
889    15
890    14
Length: 891, dtype: int64

##### df['칼럼이름'].value_counts()
   - 하나의 칼럼에서 각 범주의 개수를 세어줌

In [43]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [44]:
display(titanic['pclass'].value_counts())
display(titanic['pclass'].value_counts().values)  # 이런식으로 추출된 값을 배열형태로 사용할 수 있음

3    491
1    216
2    184
Name: pclass, dtype: int64

array([491, 216, 184], dtype=int64)

In [45]:
# 새로운 열을 추가하고 싶다.
# age_0 : 일괄적으로 0의 값을 할당하고 싶다.

titanic['age_0'] = 0
display(titanic.info())
display(titanic.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
 15  age_0        891 non-null    int64   
dtypes: bool(2), category(2), float64(2), int64(5), object(5)
memory usage: 87.6+ KB


None

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_0  
0    man        True  NaN  Southampton    no  False      0  
1  woman       False    C    Cherbourg   yes  False      0  
2  woman       False  NaN  Southampton   yes   True      0  
3  woman       False    C  Southampton   yes  False      0  
4    man        True  NaN  Southampton    no   True      0

In [47]:
# age의 각 값에 10을 곱한 age_by_10 컬럼 생성
titanic['age_by_10'] = titanic['age'] * 10
display(titanic.head())

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_0  age_by_10  
0    man        True  NaN  Southampton    no  False      0      220.0  
1  woman       False    C    Cherbourg   yes  False      0      380.0  
2  woman       False  NaN  Southampton   yes   True      0      260.0  
3  woman       False    C  Southampton   yes  False      0      350.0  
4    man        True  NaN  Southampton    no   True      0      350.0

In [48]:
# parch와 sibSp의 값과 1을 더한 family_no 컬럼생성
titanic['family_no'] = titanic['parch'] + titanic['sibsp'] + 1

In [49]:
# age_by_10 칼럼 값에 일괄적으로 +100 처리
titanic['age_by_10'] = titanic['age_by_10'] + 100

In [50]:
# age_0 열을 삭제하고자 한다면?
titanic.drop('age_0', axis=1).head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  family_no  
0    man        True  NaN  Southampton    no  False      320.0          2  
1  woman       False    C    Cherbourg   yes  False      480.0          2  
2  woman       False  NaN  Southampton   yes   True      360.0          1  
3  woman       False    C  Southampton   yes  False      450.0          2  
4    man        True  NaN  Southampton    no   True      450.0          1

In [51]:
# [데이터프레임].drop('칼럼명', axis=1, inplace=True)
# inplace=True라는 옵션은 원본을 두고 복사본에 열을 삭제하는 것이 아니라
# 원본에 바로 삭제를 적용한다는 옵션이디
display(titanic.head())
titanic.drop(['age_0', 'age_by_10', 'family_no'], axis=1, inplace=True)
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_0  age_by_10  \
0    man        True  NaN  Southampton    no  False      0      320.0   
1  woman       False    C    Cherbourg   yes  False      0      480.0   
2  woman       False  NaN  Southampton   yes   True      0      360.0   
3  woman       False    C  Southampton   yes  False      0      450.0   
4    man        True  NaN  Southampton    no   True      0      450.0   

   family_no  
0          2  
1          2  
2          1  
3          2  
4          1

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [52]:
display(titanic.head())
# 인덱스가 0, 1, 2인 행을 삭제해보자
titanic.drop([0, 1, 2], axis=0, inplace=True)
display(titanic.head())

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   
6         0       1    male  54.0      0      0  51.8625        S  First   
7         0       3    male   2.0      3      1  21.0750        S  Third   

     who  adult_male deck  embark_town alive  alone  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False

In [57]:
# 데이터의 타입은 항상 확인하는 것이 좋다
print(type(titanic.index))
print(type(titanic.index.values))

<class 'pandas.core.indexes.numeric.Int64Index'>
<class 'numpy.ndarray'>


In [64]:
# 0, 1, 2를 삭제한 데이터프레임에서 상위 5개 행을 출력하라
display(titanic.iloc[0:5, ])
display(titanic.loc[titanic.index.values[0:5], ])

# index이름이 6인 행을 출력하고 싶다면?
display(titanic.loc[[6], ])

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   
6         0       1    male  54.0      0      0  51.8625        S  First   
7         0       3    male   2.0      3      1  21.0750        S  Third   

     who  adult_male deck  embark_town alive  alone  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   
6         0       1    male  54.0      0      0  51.8625        S  First   
7         0       3    male   2.0      3      1  21.0750        S  Third   

     who  adult_male deck  embark_town alive  alone  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False

survived  pclass   sex   age  sibsp  parch     fare embarked  class  who  \
6         0       1  male  54.0      0      0  51.8625        S  First  man   

   adult_male deck  embark_town alive  alone  
6        True    E  Southampton    no   True

In [70]:
series_fair = titanic['fare']
print('series \n', series_fair, sep='')
print()
print('type : ', type(series_fair))

series 
3      53.1000
4       8.0500
5       8.4583
6      51.8625
7      21.0750
        ...   
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: fare, Length: 888, dtype: float64

type :  <class 'pandas.core.series.Series'>


In [77]:
# series_fair의 max, min, sum을 가져오고 싶어
print('max :', series_fair.max())
print('min :', series_fair.min())
print('sum :', series_fair.sum())
print('=' * 50)
print('discount 10% :', series_fair * 0.9)

max : 512.3292
min : 0.0
sum : 28607.491
discount 10% : 3      47.79000
4       7.24500
5       7.61247
6      46.67625
7      18.96750
         ...   
886    11.70000
887    27.00000
888    21.10500
889    27.00000
890     6.97500
Name: fare, Length: 888, dtype: float64


##### reset_index()
   > - 새로운 인덱스를 할당하는 방법
   > - 기존의 인덱스는 index 라는 새로운 칼럼으로 추가가 되어버린다.

In [79]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   
6         0       1    male  54.0      0      0  51.8625        S  First   
7         0       3    male   2.0      3      1  21.0750        S  Third   

     who  adult_male deck  embark_town alive  alone  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False

In [82]:
titanic_reset_index_df = titanic.reset_index(inplace=False)
titanic_reset_index_df.head()
# 결과를 보면 기존의 index는 'index'라는 칼럼으로 만들어 버리고
# 새로운 index를 부여한 것을 볼 수 있다.

index  survived  pclass     sex   age  sibsp  parch     fare embarked  \
0      3         1       1  female  35.0      1      0  53.1000        S   
1      4         0       3    male  35.0      0      0   8.0500        S   
2      5         0       3    male   NaN      0      0   8.4583        Q   
3      6         0       1    male  54.0      0      0  51.8625        S   
4      7         0       3    male   2.0      3      1  21.0750        S   

   class    who  adult_male deck  embark_town alive  alone  
0  First  woman       False    C  Southampton   yes  False  
1  Third    man        True  NaN  Southampton    no   True  
2  Third    man        True  NaN   Queenstown    no   True  
3  First    man        True    E  Southampton    no   True  
4  Third  child       False  NaN  Southampton    no  False