###### 2020-10-14 수요일

# Numpy : np.array 실습
> - pandas를 사용하지않고 풀어보라!

##### rating.data - 영화평점 데이터
   - loadtxt()
   - delimiter
   - dtype()

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
# pandas의 데이터프레임으로 불러 올 수도 있지만,
# numpy를 이용해서 한번 불러봅시다.

data = np.loadtxt('./실습데이터/ratings.dat', delimiter='::', dtype=np.int64)
data

# 칼럼이름 userid, movieid, 평점, 날짜

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [5]:
def arrinfo(arr):
    print('type : {}' .format(type(arr)))
    print('shape : {}' .format(arr.shape))
    print('dimension : {}' .format(arr.ndim))
    print('dtype : {}' .format(arr.dtype))
    print('Array Data : \n', arr)
    print()

In [8]:
arrinfo(data)

type : <class 'numpy.ndarray'>
shape : (1000209, 4)
dimension : 2
dtype : int64
Array Data : 
 [[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]



In [13]:
### 1. 데이터의 첫 5 행을 출력
data[0:5]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [26]:
### 2. 데이터의 형태 확인
data.shape

(1000209, 4)

In [17]:
### 3. 전체 평균 평점 계산
data[:, 2].mean()

3.581564453029317

In [23]:
### 4. data[ : , :2] 전체 행, 2번 열
data[ : , 1]

array([1193,  661,  914, ...,  562, 1096, 1097], dtype=int64)

In [52]:
### 5.사용자 아이디 수집

# 내가한 방식
user_id = np.array( list(set(data[:, 0])) )
print(type(user_id))
print(user_id)

# 강사님 방식 np.unique
user_id = np.unique(data[:, 0])
print(type(user_id))
print(user_id)

<class 'numpy.ndarray'>
[   1    2    3 ... 6038 6039 6040]
<class 'numpy.ndarray'>
[   1    2    3 ... 6038 6039 6040]


In [20]:
### 6. 전체 행 , 0번 열
data[:, 0]

array([   1,    1,    1, ..., 6040, 6040, 6040], dtype=int64)

In [59]:
### 7. 사용자별로 영화에 매긴 평점을 평균내어라
mean_user_rating = []
for user in user_id:
    user_rating = data[data[:, 0] ==  user][:, 2].mean()
    mean_user_rating.append([user, user_rating])
    
result = np.array(mean_user_rating, dtype = np.float32)
print(result[:5])
print(result.shape)
print(type(result))

# 파일저장
np.savetxt('./08_Numpy&Pandas_영화평점데이터_실습결과파일.csv', result, delimiter=',', fmt='%.1f')

[[1.        4.188679 ]
 [2.        3.7131784]
 [3.        3.9019608]
 [4.        4.1904764]
 [5.        3.1464646]]
(6040, 2)
<class 'numpy.ndarray'>


In [ ]:
### 8. 사용자 아이디별 평점 확인

In [ ]:
### 9. 리스트를 Numpy 배열로 변환